return function(cutscene)
    Game.world:addChild(ScreenFade({0,0,0}, 1))
    cutscene:detachCamera()
    cutscene:panTo(320,240, 0)
    cutscene:wait(1)
    Assets.playSound("credits")
    local credits = CreditsImage()
    Game.world:addChild(credits)
    cutscene:wait(credits:transitionIn("cutscene/credits/credits_a", 2))
    cutscene:wait(1)
    local text1 = Game.world:spawnObject(DialogueText("[speed:0.5][voice:none]GODHOME\n  by vitellary", 40, 370), 2000)
    local text2 = Game.world:spawnObject(DialogueText("[speed:0.5][voice:none]KRISTAL\n  by SylviBlossom\n  and Nyakorita", 320, 370), 2000)
    cutscene:wait(6)
    text1:remove()
    text2:remove()
    cutscene:wait(credits:transitionOut(2))
    cutscene:wait(1)
    cutscene:wait(credits:transitionIn("cutscene/credits/credits_b", 2))
    text1 = Game.world:spawnObject(DialogueText("[speed:0.5][voice:none]Original Art\n  by Ari Gibson", 40, 370), 2000)
    text2 = Game.world:spawnObject(DialogueText("[speed:0.5][voice:none]Pixel Art\n  by vitellary\n  and mothbeanie", 320, 370), 2000)
    cutscene:wait(6)
    text1:remove()
    text2:remove()
    cutscene:wait(credits:transitionOut(2))
    cutscene:wait(1)
    cutscene:wait(credits:transitionIn("cutscene/credits/credits_c", 2))
    text1 = Game.world:spawnObject(DialogueText("[speed:0.5][voice:none]Music\n  by Chris. Larkin\n  and Toby Fox", 40, 370), 2000)
    text2 = Game.world:spawnObject(DialogueText("[speed:0.5][voice:none]Special Thanks\n  Owen Shirrell\n  SylviBlossom", 320, 370), 2000)
    cutscene:wait(6)
    text1:remove()
    text2:remove()
    cutscene:wait(credits:transitionOut(2))
    cutscene:wait(1)
    local text3 = Game.world:spawnObject(DialogueText("[speed:0.5][voice:none]Thanks for playing", 178, 227), 2000)
    cutscene:wait(4)
    text3.fake_alpha = 1
    Game.world.timer:tween(2, text3, {fake_alpha = 0}, "linear", function()
        text3:remove()
    end)
    Game.world.timer:during(2, function(dt)
        text3.alpha = Utils.round(text3.fake_alpha, 0.2)
    end)
    cutscene:wait(4)
    cutscene:transitionImmediate("peak", "save_spawn")
    Game.world:addChild(ScreenFade({0,0,0}, 1))
    Kristal.saveGame(nil, Game:save("save_spawn"))
    Game:returnToMenu()
end